-- Add constraints to database schema
--Orders
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID);

--Order_items
ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT FK_ORDER_ITEMS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT FK_ORDER_ITEMS_PRODUCTS FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT FK_ORDER_ITEMS_SELLERS FOREIGN KEY (SELLER_ID) REFERENCES SELLERS (SELLER_ID);

--Payments
ALTER TABLE PAYMENTS
ADD CONSTRAINT FK_PAYMENTS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);

--Reviews
ALTER TABLE REVIEWS
ADD CONSTRAINT FK_REVIEWS_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);

--Products
ALTER TABLE PRODUCTS
ADD CONSTRAINT FK_PRODUCTS_TRANSLATION FOREIGN KEY (PRODUCT_CATEGORY_NAME) REFERENCES CATEGORY_TRANSLATION (PRODUCT_CATEGORY_NAME);

--Checks
ALTER TABLE REVIEWS
ADD CONSTRAINT CHK_REVIEW_SCORE CHECK (REVIEW_SCORE BETWEEN 1 AND 5);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT CHK_PRICE CHECK (PRICE >= 0);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT CHK_FREIGHT CHECK (FREIGHT_VALUE >= 0);

ALTER TABLE PAYMENTS
ADD CONSTRAINT CHK_PAYMENT_VALUE CHECK (PAYMENT_VALUE >= 0);

ALTER TABLE PAYMENTS
ADD CONSTRAINT CHK_INSTALLMENTS CHECK (PAYMENT_INSTALLMENTS >= 0);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CHK_WEIGHT CHECK (PRODUCT_WEIGHT_G >= 0);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CHK_LENGTH CHECK (PRODUCT_LENGTH_CM >= 0);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CHK_WIDTH CHECK (PRODUCT_WIDTH_CM >= 0);

ALTER TABLE PRODUCTS
ADD CONSTRAINT CHK_HEIGHT CHECK (PRODUCT_HEIGHT_CM >= 0);