
--Indexes optimized for analytics/ Индексы под задачу аналитики

-- Orders
CREATE INDEX IDX_ORDERS_CUSTOMER_ID ON ORDERS (CUSTOMER_ID);
CREATE INDEX IDX_ORDERS_PURCHASE_TS ON ORDERS (ORDER_PURCHASE_TIMESTAMP);
CREATE INDEX IDX_ORDERS_STATUS ON ORDERS (ORDER_STATUS);

-- Order Items
CREATE INDEX IDX_ORDER_ITEMS_ORDER_ID ON ORDER_ITEMS (ORDER_ID);
CREATE INDEX IDX_ORDER_ITEMS_PRODUCT_ID ON ORDER_ITEMS (PRODUCT_ID);
CREATE INDEX IDX_ORDER_ITEMS_SELLER_ID ON ORDER_ITEMS (SELLER_ID);

-- Reviews
CREATE INDEX IDX_REVIEWS_ORDER_ID ON REVIEWS (ORDER_ID, REVIEW_ID);
CREATE INDEX IDX_REVIEWS_SCORE ON REVIEWS (REVIEW_SCORE);

-- Payments
CREATE INDEX IDX_PAYMENTS_ORDER_ID ON PAYMENTS (ORDER_ID);

-- Products
CREATE INDEX IDX_PRODUCTS_CATEGORY ON PRODUCTS (PRODUCT_CATEGORY_NAME);

-- Customers
CREATE INDEX IDX_CUSTOMERS_UNIQUE_ID ON CUSTOMERS (CUSTOMER_UNIQUE_ID);
CREATE INDEX IDX_CUSTOMERS_STATE ON CUSTOMERS (CUSTOMER_STATE);

-- Sellers
CREATE INDEX IDX_SELLERS_STATE ON SELLERS (SELLER_STATE);