-- common statistics / общая статистика 
SELECT
	COUNT(DISTINCT O.ORDER_ID) AS ORDERS,
	COUNT(DISTINCT O.CUSTOMER_ID) AS CUSTOMERS,
	COUNT(DISTINCT OI.PRODUCT_ID) AS PRODUCTS,
	ROUND(SUM(OI.PRICE), 2) AS REVENUE,
	ROUND(SUM(OI.PRICE) / COUNT(DISTINCT O.ORDER_ID), 2) AS AVG_ORDER_VALUE
FROM
	ORDERS O
	JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
WHERE
	O.ORDER_STATUS = 'delivered';

--sales by months / продажи по месяцам
SELECT
	DATE_TRUNC('month', O.ORDER_PURCHASE_TIMESTAMP) AS MONTH,
	COUNT(DISTINCT O.ORDER_ID) AS ORDERS,
	ROUND(SUM(OI.PRICE) / COUNT(DISTINCT O.ORDER_ID), 2) AS AVG_ORDER_VALUE
FROM
	ORDERS O
	JOIN ORDER_ITEMS OI ON O.ORDER_ID = OI.ORDER_ID
WHERE
	O.ORDER_STATUS = 'delivered'
GROUP BY
	1;

--sales by categories / продажи по категориям
SELECT
	T.PRODUCT_CATEGORY_NAME_ENGLISH,
	COUNT(OI.ORDER_ITEM_ID) AS ITEMS_SOLD,
	ROUND(SUM(OI.PRICE), 2) AS REVENUE,
	ROUND(AVG(OI.PRICE), 2) AS AVG_PRICE
FROM
	ORDER_ITEMS OI
	JOIN ORDERS O ON O.ORDER_ID = OI.ORDER_ID
	JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
	LEFT JOIN CATEGORY_TRANSLATION T ON P.PRODUCT_CATEGORY_NAME = T.PRODUCT_CATEGORY_NAME
WHERE
	O.ORDER_STATUS = 'delivered'
GROUP BY
	1
ORDER BY
	REVENUE DESC;

--Top-10 categories / топ-10 категорий
SELECT
	T.PRODUCT_CATEGORY_NAME_ENGLISH,
	ROUND(SUM(OI.PRICE), 2) AS REVENUE
FROM
	ORDER_ITEMS OI
	JOIN ORDERS O ON O.ORDER_ID = OI.ORDER_ID
	JOIN PRODUCTS P ON OI.PRODUCT_ID = P.PRODUCT_ID
	LEFT JOIN CATEGORY_TRANSLATION T ON P.PRODUCT_CATEGORY_NAME = T.PRODUCT_CATEGORY_NAME
WHERE
	O.ORDER_STATUS = 'delivered'
GROUP BY
	1
ORDER BY
	REVENUE DESC
LIMIT
	10;

--Top-10 items / топ-10 товаров
SELECT
	OI.PRODUCT_ID,
	COUNT(*) AS ITEMS_SOLD,
	ROUND(SUM(OI.PRICE), 2) AS REVENUE
FROM
	ORDER_ITEMS OI
	JOIN ORDERS O ON O.ORDER_ID = OI.ORDER_ID
WHERE
	O.ORDER_STATUS = 'delivered'
GROUP BY
	OI.PRODUCT_ID
ORDER BY
	REVENUE DESC
LIMIT
	10;